### ISSUE TITLE
Is there any way to add initial value in form field in HTML file?

### ISSUE THREAD

**Issue by RamrajCh** [pshreyam/food-express#20]
Form `CartAddFoodForm`:
`https://github.com/pshreyam/food-express/blob/main/cart/forms.py`

and the view from `https://github.com/pshreyam/food-express/blob/main/cart/views.py`:

    def cart_detail(request):
        cart = Cart(request)
        quantity_update_form = CartAddFoodForm()
        return render(request, 'cart/cart_detail.html', {'cart': cart, 'quantity_update_form': quantity_update_form})

and HTML file `https://github.com/pshreyam/food-express/blob/main/cart/templates/cart/cart_detail.html`

I want to set ```{{ quantity_update_form.quantity}}```  field to ```item.quantity```  `line 45`and
```{{ quantity_update_form.override|default:True }}``` field to ```true``` `line 46`.  

Is there any way?

**Comment by RamrajCh** [comment]
So, Haha

I kind of solve problem a long way.
```
 <form action="{% url 'cart:cart_add' food.id %}" method="post">
                                            <select name="quantity" id="id_quantity">
                                                <option value="1" {% if  quantity == 1 %}selected{% endif %}>1</option>
                                              
                                                <option value="2" {% if  quantity == 2 %}selected{% endif %}>2</option>
                                              
                                                <option value="3" {% if  quantity == 3 %}selected{% endif %}>3</option>
                                              
                                                <option value="4" {% if  quantity == 4 %}selected{% endif %}>4</option>
                                              
                                                <option value="5"{% if  quantity == 5 %}selected{% endif %}>5</option>
                                              
                                                <option value="6" {% if  quantity == 6 %}selected{% endif %}>6</option>
                                              
                                                <option value="7"{% if  quantity == 7 %}selected{% endif %}>7</option>
                                              
                                                <option value="8" {% if  quantity == 8 %}selected{% endif %}>8</option>
                                              
                                                <option value="9" {% if  quantity == 9 %}selected{% endif %}>9</option>
                                              
                                                <option value="10" {% if  quantity == 10 %}selected{% endif %}>10</option>
                                              
                                              </select>
                                              <input type="hidden" name="override" value="True" id="id_override">
                                            <input type="submit" value="Update">
                                            {% csrf_token %}
                                        </form>
                                    </td>
                                    <td>
                                        <form action="{% url 'cart:cart_remove' food.id %}" method="post">
                                            <input type="submit" value="Remove">
                                            {% csrf_token %}
                                        </form>
```
 Problem is solved, but I have not used `quantity_update_form` . So, I would not close the issue, let it be open and maybe you guys know any idea.

**Comment by pshreyam** [comment]
> Form `CartAddFoodForm`:
> `https://github.com/pshreyam/food-express/blob/main/cart/forms.py`
> 
> and the view from `https://github.com/pshreyam/food-express/blob/main/cart/views.py`:
> 
> ```
> def cart_detail(request):
>     cart = Cart(request)
>     quantity_update_form = CartAddFoodForm()
>     return render(request, 'cart/cart_detail.html', {'cart': cart, 'quantity_update_form': quantity_update_form})
> ```
> 
> and HTML file `https://github.com/pshreyam/food-express/blob/main/cart/templates/cart/cart_detail.html`
> 
> I want to set `{{ quantity_update_form.quantity}}` field to `item.quantity` `line 45`and
> `{{ quantity_update_form.override|default:True }}` field to `true` `line 46`.
> 
> Is there any way?

You could override it prior to passing it in the view, couldn't you?
Or does it have to be dynamic?

**Comment by RamrajCh** [comment]
Yeah, but you have to override for each and every item in cart which is saved in Cart_Item model. In views, how to pass form for each item? Is there any way because what you propose is the best solution.
